### ISSUE TITLE
Notice is too wide

### ISSUE THREAD

**Issue by eliorivero** [Automattic/dops-components#74]
<img width="883" alt="too wide" src="https://cloud.githubusercontent.com/assets/1041600/21531081/10c70ada-cd24-11e6-9dd2-219f71f948d7.png">

It's solved after modifying this rule 
```css
@media (min-width: 1041px) {
    .global-notices {
      right: 32px;
      max-width: calc( 100% - 200px);
} }
```

cc @MichaelArestad @jeffgolenski
